In [1]:
import numpy as np

In [2]:
arr = np.array([[2,5,12],
                [23,9,18],
                [11,13,17]])

In [3]:
print(arr[1,0])
print(arr[2,2])

23
17


In [5]:
print(arr[-1,-2])
print(arr[-2,-2])

13
9


In [7]:
#if we want to print a specific portion 
print(arr[0:1,0:2]) #here 0 will included but 1 will not similarly 0 will included and 2 will not 
print(arr[0:2,0:2])

[[2 5]]
[[ 2  5]
 [23  9]]


In [8]:
print(arr[::2,::2]) #means it will skip two rows and 2 coloumns every time it is printing

[[ 2 12]
 [11 17]]


In [17]:
slice_arr = arr[0, :2]
slice_arr[0] = 99

In [20]:
print(arr[0]) #orignal will change 

[99  5 12]


In [21]:
copy_arr = arr[1].copy()
copy_arr[0] = 234

In [23]:
print(arr[1])

[23  9 18]
