In [4]:
import numpy as np

In [6]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [10]:
print(np.zeros((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
print(np.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
print(np.full((3,3),4))

[[4 4 4]
 [4 4 4]
 [4 4 4]]


In [14]:
print(np.arange(0,16,4)) #print 0 to 15 with the gap of 4

[ 0  4  8 12]
