In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [4]:
print(np.zeros((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
print(np.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [6]:
print(np.full((3,3),4))

[[4 4 4]
 [4 4 4]
 [4 4 4]]


In [7]:
print(np.arange(0,16,4)) #print 0 to 15 with the gap of 4

[ 0  4  8 12]


In [10]:
print(np.linspace(0,1,5)) #split in 5 equal parts 

[0.   0.25 0.5  0.75 1.  ]


In [11]:
print(np.eye(3)) #it will print the identity matrix (all diaognal will be 1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
print(np.diag([1,2,6]))

[[1 0 0]
 [0 2 0]
 [0 0 6]]


In [14]:
np.array([1,5,6],dtype=float)

array([1., 5., 6.])

In [16]:
arr = np.array([5.3,7.9,9.1])
print(arr.astype(int))

[5 7 9]
